# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: "Lint, Test, and Build Application"
    jobs:
      - job: build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.12.1'
            displayName: 'Install Node.js'
          - script: |
              npm install -g @angular/cli
              npm install
            displayName: 'npm install'
          - script: |
              npm run build
            displayName: 'Build bundle'
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: 'dist/movie-app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
          - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            artifact: core
  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: "Deploy"
        displayName: "Deploy to Production"
        steps:
          - download: current
            artifact: core
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Azure App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'TT Prime(5779ca5c-825c-4a92-8a08-4d5676575a47)'
              appType: 'webAppLinux'
              WebAppName: 'craig-salajan'
              deployToSlotOrASE: true
              ResourceGroupName: 'teragon-technologies_group'
              SlotName: 'production'
              packageForLinux: '$(Pipeline.Workspace)/core/$(Build.BuildId).zip'

