# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  repositories:
    - repository: templates
      type: git
      name: 'Internal Projects/Teragon-Pipelines'

variables:
  appName: 'craig-salajan'
  azureSubscription: 'TT Prime Subscription'
  azureStorage: 'teragonassetstorage'
  azureStorageContainer: 'craig-salajan'
  assetSourcePath: '$(Build.SourcesDirectory)/dist/ui/browser'
  webAppName: 'craig-salajan'
  dockerRegistryServiceConnection: '7eef203e-46d6-4ed2-86f1-adfc3182ef8c'
  imageRepository: 'craig-salajan'
  containerRegistry: 'teragontechnologies.azurecr.io'
  dockerfilePath: '.'
  tag: '$(Build.BuildId)'
  appType: 'webAppContainer'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

extends:
  template: angular-universal-build-deploy.yml@templates
  parameters:
    appName: $(appName)
    azureStorage: $(azureStorage)
    azureStorageContainer: $(azureStorageContainer)
    assetSourcePath: $(assetSourcePath)
    dockerfilePath: $(dockerfilePath)
    dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
    containerRegistry: $(containerRegistry)
    imageRepository: $(imageRepository)
    tag: $(tag)
    webAppName: $(webAppName)
    appType: $(appType)
    azureSubscription: $(azureSubscription)
    isMain: $(isMain)
