# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  repositories:
    - repository: templates
      type: git
      name: 'Internal Projects/Teragon-Pipelines'

variables:
  appName: 'craig-salajan'
  azureSubscription: 'TT Prime(5779ca5c-825c-4a92-8a08-4d5676575a47)'
  azureStorage: 'teragonassetstorage'
  azureStorageContainer: 'craig-salajan'
  assetSourcePath: '$(Build.SourcesDirectory)/dist/ui/browser'
  webAppName: 'craig-salajan'
  dockerRegistryServiceConnection: '6499f2c0-1860-4f5f-ade6-3bd6769f907b'
  imageRepository: 'craig-salajan'
  containerRegistry: 'teragontechnologies.azurecr.io'
  dockerfilePath: '.'
  tag: '$(Build.BuildId)'
  appType: 'webAppContainer'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

extends:
  template: angular-universal-build-deploy.yml@templates
  parameters:
    appName: $(appName)
    azureStorage: $(azureStorage)
    azureStorageContainer: $(azureStorageContainer)
    assetSourcePath: $(assetSourcePath)
    dockerfilePath: $(dockerfilePath)
    dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
    containerRegistry: $(containerRegistry)
    imageRepository: $(imageRepository)
    tag: $(tag)
    webAppName: $(webAppName)
    appType: $(appType)
    azureSubscription: $(azureSubscription)
    isMain: $(isMain)
trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: "Lint, Test, and Build Application"
    jobs:
      - job: build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.15.0'
            displayName: 'Install Node.js'
          - script: |
              npm install -g @angular/cli
              npm install
            displayName: 'npm install'
          - script: |
              npm run build
            displayName: 'Build bundle'
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: 'dist/movie-app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
          - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            artifact: core
  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: "Deploy"
        displayName: "Deploy to Production"
        steps:
          - download: current
            artifact: core
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Azure App Service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'TT Prime(5779ca5c-825c-4a92-8a08-4d5676575a47)'
              appType: 'webAppLinux'
              WebAppName: 'craig-salajan'
              deployToSlotOrASE: true
              ResourceGroupName: 'teragon-technologies_group'
              SlotName: 'production'
              packageForLinux: '$(Pipeline.Workspace)/core/$(Build.BuildId).zip'

